### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by altindas** [XUJINKAI/OneQuick#95]
It's getting an error when I open the onequick. It was working on W10, now I have W11. You can see the crash error. 
![Ekran görüntüsü 2024-09-16 113828](https://github.com/user-attachments/assets/4860c198-d3ca-4c3b-814f-928381591962)
![Ekran görüntüsü 2024-09-16 113746](https://github.com/user-attachments/assets/56037a27-9924-492f-a31b-56d8d0741cb3)

**Comment by altindas** [comment]
Could you please upload older version ?

**Comment by XUJINKAI** [comment]
please go to event viewer (eventvwr.msc), click Windows log, application. Check if there is anything about the onequick crash?

btw, what is your system language?

**Comment by altindas** [comment]
Turkish language. Nothing output on eventvwr. Could you upload older version ? It was working perfectly

**Comment by altindas** [comment]
Application: OneQuick.exe
CoreCLR Version: 8.0.824.36612
.NET Version: 8.0.8
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'OneQuick.Program.WinApp.License' threw an exception.
 ---> System.Runtime.InteropServices.COMException (0x80070424): Belirtilen hizmet, yüklü bir hizmet olarak yok.

Belirtilen hizmet, yüklü bir hizmet olarak yok.

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.Services.Store.IStoreContextStaticsMethods.GetDefault(IObjectReference _obj)
   at Windows.Services.Store.StoreContext.GetDefault()
   at OneQuick.Program.WinApp.MsStore.GetStoreContext()
   at OneQuick.Program.WinApp.License..ctor()
   at OneQuick.Program.WinApp.License..cctor()
   --- End of inner exception stack trace ---
   at OneQuick.Program.WinApp.License.get_Instance()
   at OneQuick.Program.App.InitBuisness()
   at OneQuick.Program.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at OneQuick.Program.App.Main()

**Comment by XUJINKAI** [comment]
That's odd, the Windows Store is throwing an exception. 
I will upload a fixed version to bypass the error in the license check method, then you can open the app.

You can try logout of the store app, then run **wsreset** in the admin cmd to reset the store, and log in again. It might work.

**Comment by altindas** [comment]
Will you upload here or store ?

**Comment by XUJINKAI** [comment]
Store. It may take several hours to shown in store, up to 3 days.

**Comment by XUJINKAI** [comment]
Fixed version (10.1.4) is now available in store. Thanks for using and reporting the bugs.
