### ISSUE TITLE
Crashing again

### ISSUE THREAD

**Issue by altindas** [XUJINKAI/OneQuick#96]
Application: OneQuick.exe
CoreCLR Version: 8.0.824.36612
.NET Version: 8.0.8
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at OneQuick.Config.Profile.ProfileExtension.ApplyEngine(MainProfile profile)
   at OneQuick.Program.App.InitBuisness()
   at OneQuick.Program.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at OneQuick.Program.App.Main()

Hatalı uygulama adı: OneQuick.exe, sürüm: 0.0.0.0, zaman damgası: 0x00000000
Hatalı modül adı: unknown, sürüm: 0.0.0.0, zaman damgası: 0x00000000
Özel durum kodu: 0x00000000
Hata uzaklığı 0x0000000000000000
Hatalı işlem kimliği: 0x0x22FC
Uygulama başlangıç zamanı: 0x0x1DB0A513155EC81
Hatalı uygulama yolu: C:\Program Files\WindowsApps\55774JinkaiXu.252258CF1F9E6_10.1.4.0_x64__p5dcp4q3yn5jt\OneQuick\OneQuick.exe
Hatalı modül yolu: unknown
Rapor kimliği: 1c257cca-d40b-41be-8a87-4c469db51e0a
Hatalı paket tam adı: 55774JinkaiXu.252258CF1F9E6_10.1.4.0_x64__p5dcp4q3yn5jt
Hatalı paketle ilgili uygulama kimliği: App

I tried to remove local/packages/55774JinkaiXu.252258CF1F9E6_p5dcp4q3yn5jt but it still happens.

**Comment by XUJINKAI** [comment]
Exit App first, then try to remove these folders:
\<Users>\AppData\Local\Packages\55774JinkaiXu.252258CF1F9E6_p5dcp4q3yn5jt
\<Users>\AppData\Local\OneQuick
\<My Documents>\OneQuick

If still not work, please tell me more detail:
Is app shows any messagebox when crash?
Paste contents in \log folder, \profile\profile.json, and \setting\setting.json (these are in LocalState folder)

**Comment by altindas** [comment]
Its not working.

![Ekran görüntüsü 2024-09-19 171857](https://github.com/user-attachments/assets/52539345-4d98-428d-b2b4-312ca583555a)
![Ekran görüntüsü 2024-09-19 171848](https://github.com/user-attachments/assets/3f32b91a-7f4e-4e35-be8e-f274df1b31ef)
![Ekran görüntüsü 2024-09-19 171903](https://github.com/user-attachments/assets/c26d3a85-5d58-4517-ba49-c8666f5c1d6a)

**Comment by XUJINKAI** [comment]
UnauthorizedAccessException means app has no rights to access the folder or file:
\<Users>\AppData\Local\Packages\55774JinkaiXu.252258CF1F9E6_p5dcp4q3yn5jt\LocalState\backup
\<Users>\AppData\Local\Packages\55774JinkaiXu.252258CF1F9E6_p5dcp4q3yn5jt\LocalState\profile\profile.json
The folder is designed for app use but for some reason system not allowed.

You can uninstall OneQuick first, make sure whole \<Users>\AppData\Local\Packages\55774JinkaiXu.252258CF1F9E6_p5dcp4q3yn5jt folder is disappeared, and there is NO **OneQuick** folder in your **My Documents** folder, then reinstall the app.

If not work, maybe you should change the folder permission. (right click menu -> properties -> security)

**Comment by altindas** [comment]
It's not working. And sometimes it makes Windows crash.

**Comment by altindas** [comment]
Is there any progress ?

**Comment by XUJINKAI** [comment]
I will try to fix and upload a new version to store in about 7 days. I am not sure if it will work.
If it not, you can wait for a desktop version.

**Comment by altindas** [comment]
Okay, when will you upload desktop version ?

**Comment by XUJINKAI** [comment]
I'm not sure, more than a month. Sorry.

And desktop version is always Free version, has NO Pro feature.

**Comment by altindas** [comment]
If you have any version for desktop please upload. I can use with bugs :)

**Comment by XUJINKAI** [comment]
10.2 now at store.
